### ISSUE TITLE
Custom Global Markdown not being applied.

### ISSUE THREAD

**Issue by bigmanshawn** [bigmanshawn/ConanEvolved_Merchants#8]

**Comment by bigmanshawn** [comment]
Could not replicate, need more specifics on this issue.

**Comment by Tirocupidus** [comment]
The Markdown setting is saving correctly, it just isn't being applied correctly. It seems that 0.6 is hardcoded somewhere where it should reference the Markdown value.

**Comment by bigmanshawn** [comment]
Thank you for clarification I will look again.

**Comment by bigmanshawn** [comment]
Issue might be redundant since we are changing from a mark down to mark up system with issue #12 which is slated for 1.2

**Comment by bigmanshawn** [comment]
Looks like we were referencing an old variable when we switched over to the new global variables, fixed now during the update to a global mark up
