### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by Midnighit** [bigmanshawn/ConanEvolved_Merchants#9]
Items are being pushed out of the screen when the list of items for sale grows too long. A fixed size with a scrollbar would fix the issue.

List with buttons still just inside: [http://i.imgur.com/8CP99Mr.jpg](url)
List with button pushed of the screen [http://i.imgur.com/3cs2lNk.jpg](url)

**Comment by bigmanshawn** [comment]
This issue has been fixed in 562fab6e5e58679a25bcf59ce89a5d04bd1cb27b as well as some other scaling issues with the UI.
